### ISSUE TITLE
About input fragment file and anchors

### ISSUE THREAD

**Issue by dwbaron** [igashov/DiffLinker#2]
Hi, you guys did a good job about connecting diffusion model and de novo design based on fragments.
I'm now working on design small molecules, I want to use this model to work, but after I run the code I met some problems.
1. Accroding to the help instructions, If I got 3 mol fragments, should I put them into one pdb file? And how the format of this kind of PDB file looks like, is there any example input file? 
2. the argument anchor, is that mean the atoms id in the PDB file that link the fragments?
I'm looking forward to your help ~

**Comment by igashov** [comment]
Hi @dwbaron,

Thank you for the feedback, we are glad that you liked our work!

1. Yes, all the input fragments should be in the same pdb, mol, mol2 or sdf file. Please check examples here: https://huggingface.co/spaces/igashov/DiffLinker/tree/main/examples

2. Yes, you can pass the information about atoms to be connected specifying their IDs in `--anchors` argument (comma-separated numbers, e.g. `--anchors 4,12,20`). To get the right IDs, you can open your file with fragments in PyMOL and show atom ID labels (as shown in the figure below).

<img width="863" alt="Screenshot 2022-11-10 at 16 38 44" src="https://user-images.githubusercontent.com/19591226/201138957-8780df3b-6d40-4b67-8c69-153ecfc8f0f1.png">

Please let me know if you have other questions!

**Comment by dwbaron** [comment]
> Hi @dwbaron,
> 
> Thank you for the feedback, we are glad that you liked our work!
> 
> 1. Yes, all the input fragments should be in the same pdb, mol, mol2 or sdf file. Please check examples here: https://huggingface.co/spaces/igashov/DiffLinker/tree/main/examples
> 2. Yes, you can pass the information about atoms to be connected specifying their IDs in `--anchors` argument (comma-separated numbers, e.g. `--anchors 4,12,20`). To get the right IDs, you can open your file with fragments in PyMOL and show atom ID labels (as shown in the figure below).
> 
> <img alt="Screenshot 2022-11-10 at 16 38 44" width="863" src="https://user-images.githubusercontent.com/19591226/201138957-8780df3b-6d40-4b67-8c69-153ecfc8f0f1.png">
> 
> Please let me know if you have other questions!

Thanks for u help, it solved the problems~
