### ISSUE TITLE
Question：given the limitation of pocket but without limitataion of --anchors

### ISSUE THREAD

**Issue by MachineGUN001** [igashov/DiffLinker#8]
hi, 

if using `generate_with_protein.py` or `generate_with_pocket.py` method, the para --anchors is necessary. however, 
In order to take into account the diversity of compounds generated, is there any approach that takes into account the combination and limitation of pockets but doesn't limit the location of the anchors for the fragment links?

many many thanks,

Sh-Y

**Comment by igashov** [comment]
Hello,

These scripts [do not require](https://github.com/igashov/DiffLinker/blob/main/generate_with_protein.py#L59) --anchors parameter to be specified. However, if you don't specify anchors you need to make sure that you use the model that was trained without anchors. In case of pocket conditioning, [there is](https://zenodo.org/record/7775568/files/pockets_difflinker_full_no_anchors.ckpt?download=1) such a model.

Hope it help!

Best regards
Ilia

**Comment by MachineGUN001** [comment]
hi, Llia,

thanks for your kind explanation. I'll give a try to do the modification as you mentioned.
this issue will be closed. 

Best,

Sh-Y
